# Generated by Django 5.0.3 on 2024-04-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0007_rename_customize_customization_and_more'),
        ('gift_seller', '0007_alter_product_sellerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerInfo',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
