# Generated by Django 5.0.3 on 2024-04-18 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0008_delete_sellerinfo_delete_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='address',
            new_name='housename',
        ),
    ]
