# Generated by Django 5.0.3 on 2024-04-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0009_rename_address_userinformation_housename'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default='1', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='password',
            field=models.CharField(default='1', max_length=8),
            preserve_default=False,
        ),
    ]
