# Generated by Django 5.0.3 on 2024-04-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0010_seller_password_userinformation_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userr', models.CharField(max_length=150)),
                ('product', models.CharField(max_length=150)),
                ('total_item', models.CharField(max_length=150)),
                ('total_price', models.CharField(max_length=150)),
                ('card_name', models.CharField(max_length=150)),
                ('card_number', models.FloatField(max_length=150)),
                ('cvv', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
    ]
