# Generated by Django 5.0.3 on 2024-04-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0011_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
