# Generated by Django 5.0.3 on 2024-04-19 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0012_remove_cartitem_product_remove_cartitem_user_and_more'),
        ('gift_seller', '0008_rename_sellerinfo_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='userr',
        ),
        migrations.AddField(
            model_name='purchases',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='gift_app.userinformation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchases',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_seller.product'),
        ),
    ]
