# Generated by Django 5.0.3 on 2024-04-04 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gift_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(upload_to='media')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_admin.category')),
            ],
        ),
    ]
