# Generated by Django 5.0.3 on 2024-04-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default='1', max_length=5),
            preserve_default=False,
        ),
    ]
