# Generated by Django 5.0.3 on 2024-04-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_seller', '0002_product_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
    ]
