# Generated by Django 5.0.3 on 2024-04-14 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0003_order_orderitem_shippingaddress_delete_cart'),
        ('gift_seller', '0003_remove_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellerinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_app.sellerinfo'),
        ),
    ]
