# Generated by Django 5.0.3 on 2024-04-16 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_admin', '0001_initial'),
        ('gift_app', '0004_customize_remove_orderitem_order_and_more'),
        ('gift_seller', '0004_product_sellerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(upload_to='media')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_admin.category')),
                ('sellerinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_app.sellerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(upload_to='media')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_admin.category')),
                ('sellerinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_app.sellerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(upload_to='media')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_admin.category')),
                ('sellerinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_app.sellerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Hoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(upload_to='media')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_admin.category')),
                ('sellerinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_app.sellerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Scrapbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(upload_to='media')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_admin.category')),
                ('sellerinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_app.sellerinfo')),
            ],
        ),
    ]
