# Generated by Django 5.0.3 on 2024-04-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift_seller', '0005_bottle_candle_frame_hoop_scrapbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='sellerinfo',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='category',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='sellerinfo',
        ),
        migrations.RemoveField(
            model_name='hoop',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hoop',
            name='sellerinfo',
        ),
        migrations.RemoveField(
            model_name='scrapbook',
            name='category',
        ),
        migrations.RemoveField(
            model_name='scrapbook',
            name='sellerinfo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sellerinfo',
            new_name='sellerInfo',
        ),
        migrations.DeleteModel(
            name='Bottle',
        ),
        migrations.DeleteModel(
            name='Candle',
        ),
        migrations.DeleteModel(
            name='Frame',
        ),
        migrations.DeleteModel(
            name='Hoop',
        ),
        migrations.DeleteModel(
            name='Scrapbook',
        ),
    ]
