# Generated by Django 5.0.3 on 2024-04-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0007_rename_customize_customization_and_more'),
        ('gift_seller', '0006_remove_candle_category_remove_candle_sellerinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellerInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_app.seller'),
        ),
    ]
