# Generated by Django 5.0.3 on 2024-04-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_seller', '0008_rename_sellerinfo_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
